version: '3'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=cmpuser
      - POSTGRES_PASSWORD=cmppassword
      - POSTGRES_DB=cmpdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cmpuser -d cmpdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=cmpuser
      - POSTGRES_PASSWORD=cmppassword
      - POSTGRES_DB=cmpdb
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always
    
  deployment-engine:
    build: ./deployment_engine
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./deployment_engine:/app
      - deployment_data:/data
    restart: always

volumes:
  postgres_data:
  deployment_data:
