version: '3'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=cmpuser
      - POSTGRES_PASSWORD=cmppassword
      - POSTGRES_DB=cmpdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cmpuser -d cmpdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=cmpuser
      - POSTGRES_PASSWORD=cmppassword
      - POSTGRES_DB=cmpdb
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always
    
  # Deployment Engine Container
  deployment-engine:
    build:
      context: ./deployment_engine
      dockerfile: Dockerfile
    volumes:
      - ./deployment_engine:/app
      - deployment_data:/data
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - API_URL=http://api:8000
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db
      - api
    restart: always

volumes:
  postgres_data:
  deployment_data:

networks:
  app-network:
