version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: cmp-postgres
    restart: always
    environment:
      POSTGRES_USER: cmpuser
      POSTGRES_PASSWORD: cmppassword
      POSTGRES_DB: cmpdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

